spring.application.name=Gigzy

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/gigzy
server.address=0.0.0.0


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gigzy45@gmail.com
spring.mail.password=ppiv uryh gkzq pyyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true